.gitignore, firmware/doom/.gitignore
Remove useless git ignore from doom folder, add all to main gitignore
=> fix: some fixes for gitignore files

firmware/keira/sdcard/wifi_test.lua, firmware/keira/src/apps/lua/lualilka_wifi.cpp, firmware/keira/src/apps/lua/lualilka_wifi.h, firmware/keira/src/apps/lua/luarunner.cpp
WiFi: add minimal functional for wifi for lua scripts, default like connect, disconnect, status and scan available neworks
(rssi, wifi_channel, encrypt type WIP)
=> WiFi: add minimal functional for wifi for lua scripts

firmware/keira/src/apps/launcher.cpp
closes https://github.com/and3rson/lilka/issues/52
=> allow browser in launcher.app to work with different cased extensions 

firmware/keira/targets.py
Утиліта тепер працює і під ШИНДОУС!!!!
=> fix addr2line for windows pc

firmware/keira/src/apps/lua/lualilka_display.cpp, firmware/keira/src/apps/lua/lualilka_imageTransform.cpp, sdk/lib/lilka/src/lilka/display.cpp
keira: fix crash when attempting to draw transformed image with zero width or height
=> keira: fix Lua transform issues

firmware/keira/src/appmanager.cpp, firmware/keira/src/appmanager.h, firmware/keira/src/main.cpp, firmware/keira/src/services/network.cpp, firmware/keira/src/services/network.h, firmware/keira/src/services/screenshot.cpp, firmware/keira/src/services/screenshot.h, sdk/lib/lilka/src/lilka/controller.cpp, sdk/lib/lilka/src/lilka/controller.h
keira: add screenshot hotkey (select + start)
keira: implement toasts
keira: show toast on WiFi connect/disconnect
sdk: add State::peekState
=> Add `ScreenshotService`, add toasts

firmware/keira/src/apps/launcher.cpp
"GPIO-мененджер" -> "GPIO-менеджер"
=> fix GPIO manager title menu

firmware/keira/platformio.ini
=> Explicit set version for NimBLE-Arduino dependency for ESP32-BLE-Gamepad library

firmware/keira/sdcard/serial/gps.lua, firmware/keira/sdcard/serial/gps_readn.lua, firmware/keira/sdcard/serial/readwrite.lua, firmware/keira/src/apps/lua/lualilka_serial.cpp, firmware/keira/src/apps/lua/lualilka_serial.h, firmware/keira/src/apps/lua/luarunner.cpp
для роботи з UART1 (RX 47, TX 48)
=> Розширення LUA API

firmware/keira/src/apps/lua/lualilka_serial.cpp
Fix code format after merging lualilka_serial
=> Code quality fixes

sdk/lib/lilka/src/lilka.cpp
Should fix some SD cards initialization
=> Reorder display/sd initialization

firmware/keira/sdcard/gps/gps_tracker.lua, firmware/keira/sdcard/gps/libs/gps.lua, firmware/keira/sdcard/gps/modules/tracker.lua, firmware/keira/sdcard/serial/gps.lua, firmware/keira/sdcard/serial/gps_readn.lua, firmware/keira/sdcard/serial/readwrite.lua, firmware/keira/src/apps/lua/lualilka_http.cpp, firmware/keira/src/apps/lua/lualilka_http.h, firmware/keira/src/apps/lua/lualilka_sdcard.cpp, firmware/keira/src/apps/lua/lualilka_serial.cpp, firmware/keira/src/apps/lua/luarunner.cpp
LUA API: http module
GPS tracker - example of using API serial and http
=> GPS tracker LUA application

firmware/keira/src/apps/pastebin/pastebinApp.cpp
=> fix: fix of Alder's remarks

firmware/keira/src/apps/statusbar.cpp
#159 
Show free RAM as number (151kB) instead of icon
=> StatusBarApp: show free RAM as number

firmware/keira/src/apps/launcher.cpp, firmware/keira/src/apps/launcher.h, firmware/keira/src/services/network.cpp, firmware/keira/src/services/network.h
added WIFI_KEIRA_NAMESPACE for wifi settings in nvs
=> WiFi tx power change option in settings, autoload from nvs

firmware/keira/src/apps/settings/sound.cpp, firmware/keira/src/apps/settings/sound.h
=> Reimplementation of sound settings

firmware/keira/src/apps/demos/letris.cpp, firmware/keira/src/apps/fmanager.cpp, firmware/keira/src/apps/gpiomanager.cpp, firmware/keira/src/apps/settings/sound.cpp, firmware/sample/src/main.cpp, sdk/lib/lilka/src/main.cpp
Already implemented delay inside update()
=> Remove unnecessary ui delays

.github/workflows/firmware.yml, .github/workflows/sdk.yml, firmware/keira/src/services/screenshot.cpp, sdk/lib/lilka/platformio.ini, sdk/lib/lilka/src/lilka/ble_server.h
ci: run firmware job on PRs & commits to main
=> Fix builds for keira, doom & sdk and add GHA checks

hardware/v2/main.kicad_pcb, hardware/v2/main.kicad_sch, hardware/v2/main_rounded.kicad_pcb
```
Docs were updated on Jan 2 to these values. Assuming it was correct.
Link: 7412343db23f ("Fix component values and count")
```
Дякую.
=> Update C2, C3 value from 1uF to 10uF in KiCAD files

firmware/keira/src/apps/lua/lualilka_state.cpp
Fix deserialization of string values from state
=> LUA API state

firmware/keira/src/apps/lua/lualilka_util.cpp, sdk/addons/lualilka/library/util.lua
=> LUA API util new methods

firmware/keira/src/apps/lua/lualilka_display.cpp, sdk/addons/lualilka/library/display.lua
- setTextBound
- setTextColor
- colors enum
=> LUA API display new methods

sdk/lib/lilka/src/lilka/display.cpp
https://github.com/moononournation/Arduino_GFX/pull/460#issuecomment-2129659986
=> reduce memory consumption and use right way to getTextWidth

firmware/keira/src/apps/gpiomanager.cpp, firmware/keira/src/apps/gpiomanager.h
Добавив режими для PWN (відсотково) та Square waves (частотний генератор).
**UPD:**
Зміна режиму так само як і між INPUT/OUTPUT кнопкою D (так як було)
Кнопка A - міняє значення 0-100% (так було)
Кнопка С - міняє частота (нова кнопка) 100 - 20к
**Важливо!** режим PWM можна виставляти для кожного піна окремо, але їх 6, а таймерів доступно тільки 4, тому два піна будуть використовувати таку саму частоту (візуально буде показуватись зміна, але це не бага).
(протестував на осцилографі).
[osc.webm](https://github.com/user-attachments/assets/a949b37a-793a-4c5c-b856-3a491c6ed93c)
=> feat(#222): Implement PWM and square wave functionality

docs/hardware/schematics.rst
closes https://github.com/lilka-dev/lilka/issues/239
=> update links to kicanvas.org
